{% set name = "bayesmbar" %}
{% set version = "0.1.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/bayesmbar-{{ version }}.tar.gz
  sha256: 00696497d90583dde2607ade02e5fdac715c4b6c04bbafd41ab4706652c0d493

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.6.0
    - jaxlib >=0.6.0
    - blackjax >=1.2.3
    - networkx >=3.3
    - tqdm >=4.66.5
    - scipy ==1.16.0

test:
  imports:
    - bayesmbar
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/DingGroup/BayesMBAR
  summary: 'Bayesian Multistate Bennett Acceptance Ratio Method'
  description: |
    This repository contains the code for the Bayesian Multistate Bennett Acceptance Ratio Method as described 
    in the paper. BayesMBAR is a Bayesion generalization of the Multistate Bennett Acceptance Ratio (MBAR) 
    method for computing free energy differences between multiple states.

  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://dinglab.io/BayesMBAR/
  dev_url: https://github.com/DingGroup/BayesMBAR

extra:
  recipe-maintainers:
    - xiki-tempula
